### ISSUE TITLE
Show critical errors via MessageBox, not just recaf-launcher.log

### ISSUE THREAD

**Issue by Yoticc** [Col-E/Recaf-Launcher#10]
For example, when I open the launcher.jar it doesn't open, I don't see MessageBox with error, to understand what happened, I have to open recaf-launcher.log to find the line with an error.
In that case log is:
```
Attempting to resolve installed Recaf version...
Recaf jar file not found: 'C:\Users\u\AppData\Roaming\Recaf\recaf.jar'
```

It would be nice to see a MessageBox with error:
```
Recaf jar file not found:
``C:\Users\u\AppData\Roaming\Recaf\recaf.jar''.
```

I think it won't be a problem to make MessageBox display via jfx

**Comment by Col-E** [comment]
> MessageBox display via jfx

The launcher has no dependency on JFX so it'd be in swing, but I agree this would be a nice to have feature for usability.

**Comment by Col-E** [comment]
Wait, are you saying when you open the launcher the GUI does not show up?

The way this works is that if you run it via `java` you get the CLI. But if you use `javaw` which is how most OS's pair `.jar` file associations you get the GUI. This is intentional, you don't wan the CLI to pop open dialog windows.

**Comment by Yoticc** [comment]
I think it's because I had jre8 and jre11 on my PC, but not jre17. This was fixed after installing jre17 when I tried to build the recaf-ui module. I used `java -jar` but at the same time tried `java.exe` and `javaw.exe` from jre8, as I remember

**Comment by zDEFz** [comment]
pointing out the obvious, javaw is not existent on linux for example

**Comment by Col-E** [comment]
32b9f95921d9b1eaaa9508b2650318a942032e43 largely accomplishes this, and addresses the confusion about `java` vs `javaw` since the GUI/CLI are now separate as of 0.5.0
