### ISSUE TITLE
How to use launcher from cli?

### ISSUE THREAD

**Issue by slava110** [Col-E/Recaf-Launcher#18]
Hi. I want to make simple cli command to decompile jar file. With programs like text editors I can just specify filename after program name (`notepad myfile.txt`). But it doesn't work with this launcher. Where can I specify file to open? Or workspace to open or stuff like that.
Also headless mode doesn't seem to work for me, recaf still opens a window even when I use `java` (not `javaw`) and specify `-x` option. And there's no `--help` or anything

**Comment by Col-E** [comment]
> how do I make a cli command to decompile a jar file

The launcher doesn't yet specify passing along arguments to Recaf. I'll add that in the next release and track it as #20 

> Also headless mode doesn't seem to work

32b9f95921d9b1eaaa9508b2650318a942032e43 - I've split the releases into a separate GUI and CLI so this is no longer an issue
