### ISSUE TITLE
Launcher opens headless when opening from cli with javaw

### ISSUE THREAD

**Issue by Janmm14** [Col-E/Recaf-Launcher#19]
And does nothing
```bat
C:\java\jdk22\bin\javaw -jar recaf-launcher-0.4.1.jar
```

**Comment by Janmm14** [comment]
Somehow now also a double-click doesn't open the GUI, wtf

**Comment by Col-E** [comment]
32b9f95921d9b1eaaa9508b2650318a942032e43 - See 0.5.0 for a definitive fix. They are now explicitly separate.
