### ISSUE TITLE
Unable to run Recaf through launcher: java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by c01dc0ffee** [Col-E/Recaf-Launcher#2]
Here's the stdout generated when using Azul Zulu 21: [stdout_zulu21.txt](https://github.com/Col-E/Recaf-Launcher/files/13186138/stdout_zulu21.txt)

Same thing with Eclipse Adoptium 17: [stdout_adoptium17.txt](https://github.com/Col-E/Recaf-Launcher/files/13186124/stdout_adoptium17.txt)

The exception `java.lang.UnsatisfiedLinkError: 'java.lang.String com.sun.javafx.font.PrismFontFactory.regReadFontLink(java.lang.String)'` is probably generated by some JavaFX incompatibility. I'm unsure if either of these runtimes have JavaFX bundled, but a quick `find` for jfx/javafx in the install directory yields nothing. Thanks in advance.

**Comment by c01dc0ffee** [comment]
I cloned the 4x branch and I'm able to build that and run it on Adoptium 17 without trouble. The `PrismFontFactory.class` bundled in the snapshot build and the one in `%AppData%/Recaf/dependencies/javafx-graphics-22-ea+11-win.jar` are SHA1-identical. It seems that the JavaFX dependencies are maybe not on the classpath.

**Comment by Col-E** [comment]
The JavaFX gradle plugin's configuration is seemingly being ignored after I updated from `0.0.13` to `0.1.0`...

**Comment by Col-E** [comment]
Reverted the JFX plugin to `0.0.14` re-run the launcher after the CI makes a new artifact and this should resolve itself

**Comment by Col-E** [comment]
oh... right I updated because we kinda needed the multiple dependency scopes.... ughh

**Comment by c01dc0ffee** [comment]
Perfect ❤
