### ISSUE TITLE
Download progress information missing

### ISSUE THREAD

**Issue by meiMingle** [Col-E/Recaf-Launcher#27]
After clicking the Update button, the interface shows Updating for a long time, and there is no information about the download/update in the console. Sometimes there is no change for several minutes or even more than ten minutes. At this time, it is impossible to confirm whether the download is still in progress or whether the download is interrupted due to an error. It would be great if a download/update progress bar could be added to the Gui interface
![image](https://github.com/user-attachments/assets/6d410f88-d930-49e9-98b0-dd683e440f2d)

**Comment by Col-E** [comment]
Added in 0.7.0
