### ISSUE TITLE
Dependencies folder needs to exist

### ISSUE THREAD

**Issue by alexyao2015** [Col-E/Recaf-Launcher#6]
First time installing the launcher. When running `java -jar recaf-launcher-0.1.3.jar update-jfx`, it attempts to download dependencies into `AppData\Roaming\Recaf\dependencies`. In my case, the `dependencies` directory did not exist and the launcher did not make an attempt to create the directory automatically. This caused the dependency download to fail.

**Comment by C0D3-M4513R** [comment]
Known: https://github.com/Col-E/Recaf/issues/740

**Comment by Col-E** [comment]
This was fixed in 0.1.4 please use the up-to-date launcher.
